//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourceProjectMVVMAndEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders_Goods
    {
        public int goodsNumber { get; set; }
        public int orderNumber { get; set; }
        public int goodsCount { get; set; }
    
        public virtual Goods Goods { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
